spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 2002
  jpa:
    hibernate:
      ddl-auto: update  # Use update for persistent DB instead of create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080

